id: P005401
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG15511
  title: གངས་ཏི་སེ་བོན་གཞུང་རིག་མཛོད་དཔེ་ཚོགས་ལེགས་གྲུབ་ཀྱི་དྲན་རྟེན་ཟིན་ཐོ།
  author: ''
  volumes:
    aaf4283a953b47a298a3e1b767f431d6:
      image_group_id: I1KG15845
      title: ''
      volume_number: 1
      total_pages: 254
      base_file: v001.txt
